/** @type {import('tailwindcss').Config} */
export default {
  content: ['index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        s1: 'var(--s1)',
        s2: 'var(--s2)',
        s3: 'var(--s3)',
        s4: 'var(--s4)',
        b1: 'var(--b1)',
        b2: 'var(--b2)',
        b3: 'var(--b3)',
        fg: 'var(--fg)',
        text: 'var(--text)',
        text2: 'var(--text2)',
        muted: 'var(--muted)',
        muted2: 'var(--muted2)',
        green: 'var(--green)',
        yellow: 'var(--yellow)',
        red: 'var(--red)',
        gold: 'var(--gold)',
        cream: 'var(--cream)',
        wood: 'var(--wood)',
        'wood-light': 'var(--wood-light)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'chart-4': 'var(--chart-4)',
        'chart-5': 'var(--chart-5)',
        'chart-6': 'var(--chart-6)',
        'chart-7': 'var(--chart-7)',
        'chart-8': 'var(--chart-8)',
        'chart-grid': 'var(--chart-grid)',
        'chart-axis': 'var(--chart-axis)',
        'chart-ink': 'var(--chart-ink)',
        'chart-ink-muted': 'var(--chart-ink-muted)',
      },
      fontFamily: {
        sans: ['Instrument Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Playfair Display', 'serif'],
      },
      borderRadius: {
        DEFAULT: '6px',
      },
    },
  },
  plugins: [],
};
